// Console profile choices shared by native frontends.
#ifndef XENIA_UI_PROFILE_OPTIONS_H_
#define XENIA_UI_PROFILE_OPTIONS_H_
namespace xe::ui {
inline constexpr const char* kLanguageNames[] = {nullptr,
                                                 "English",
                                                 "Japanese",
                                                 "German",
                                                 "French",
                                                 "Spanish",
                                                 "Italian",
                                                 "Korean",
                                                 "Traditional Chinese",
                                                 "Portuguese",
                                                 "Simplified Chinese",
                                                 "Polish",
                                                 "Russian"};

inline constexpr const char* kCountryNames[] = {nullptr,
                                                "United Arab Emirates",
                                                "Albania",
                                                "Armenia",
                                                "Argentina",
                                                "Austria",
                                                "Australia",
                                                "Azerbaijan",
                                                "Belgium",
                                                "Bulgaria",
                                                "Bahrain",
                                                "Brunei Darussalam",
                                                "Bolivia",
                                                "Brazil",
                                                "Belarus",
                                                "Belize",
                                                "Canada",
                                                nullptr,
                                                "Switzerland",
                                                "Chile",
                                                "China",
                                                "Colombia",
                                                "Costa Rica",
                                                "Czech Republic",
                                                "Germany",
                                                "Denmark",
                                                "Dominican Republic",
                                                "Algeria",
                                                "Ecuador",
                                                "Estonia",
                                                "Egypt",
                                                "Spain",
                                                "Finland",
                                                "Faroe Islands",
                                                "France",
                                                "Great Britain",
                                                "Georgia",
                                                "Greece",
                                                "Guatemala",
                                                "Hong Kong",
                                                "Honduras",
                                                "Croatia",
                                                "Hungary",
                                                "Indonesia",
                                                "Ireland",
                                                "Israel",
                                                "India",
                                                "Iraq",
                                                "Iran",
                                                "Iceland",
                                                "Italy",
                                                "Jamaica",
                                                "Jordan",
                                                "Japan",
                                                "Kenya",
                                                "Kyrgyzstan",
                                                "Korea",
                                                "Kuwait",
                                                "Kazakhstan",
                                                "Lebanon",
                                                "Liechtenstein",
                                                "Lithuania",
                                                "Luxembourg",
                                                "Latvia",
                                                "Libya",
                                                "Morocco",
                                                "Monaco",
                                                "Macedonia",
                                                "Mongolia",
                                                "Macau",
                                                "Maldives",
                                                "Mexico",
                                                "Malaysia",
                                                "Nicaragua",
                                                "Netherlands",
                                                "Norway",
                                                "New Zealand",
                                                "Oman",
                                                "Panama",
                                                "Peru",
                                                "Philippines",
                                                "Pakistan",
                                                "Poland",
                                                "Puerto Rico",
                                                "Portugal",
                                                "Paraguay",
                                                "Qatar",
                                                "Romania",
                                                "Russian Federation",
                                                "Saudi Arabia",
                                                "Sweden",
                                                "Singapore",
                                                "Slovenia",
                                                "Slovak Republic",
                                                nullptr,
                                                "El Salvador",
                                                "Syria",
                                                "Thailand",
                                                "Tunisia",
                                                "Turkey",
                                                "Trinidad And Tobago",
                                                "Taiwan",
                                                "Ukraine",
                                                "United States",
                                                "Uruguay",
                                                "Uzbekistan",
                                                "Venezuela",
                                                "Viet Nam",
                                                "Yemen",
                                                "South Africa",
                                                "Zimbabwe"};

inline constexpr const char* kSubscriptionTierNames[] = {
    "None",  nullptr, nullptr, "Silver", nullptr,
    nullptr, "Gold",  nullptr, nullptr,  "Family"};

inline constexpr const char* kGamerZoneNames[] = {"None", "Recreation", "Pro",
                                                  "Family", "Underground"};

}  // namespace xe::ui
#endif
